In [1]:
import pandas as pd
from datetime import date
import os

In [2]:
tDay=date.today()

In [3]:
quote='quote borrow: 1280-HK / 2477-HK / 1196-HK / 412-HK / 7226-HK / 7552-HK / 9696-HK / 2359-HK / 3750-HK / 564-HK / 1072-HK / 600418-CH / 688256-CH / 042660-KS / 329180-KS / 7014-JP'

In [4]:
text='''
CGSI swap BUY 500K shares 291-HK limit 24.30, POV 5% passive 
Huatai SELL 400K shares 2156-HK limit 2.65, POV 12% passive 
CLSA cover 3mn shares 601328-CH limit 7.68, Desk POV 5% passive 
CLSA cover 136K shares 1121-HK limit 1.54, POV 15% near-touch
CLSA short 40.5K shares 9636-HK limit 40.50, POV 6% passive 
CLSA short 155K shares 2473-HK limit 6.65, POV 12% passive 
CLSA cover 1mn shares 2202-HK limit 4.76, POV 5% near-touch
CLSA cover 250K shares 1280-HK limit 3.28, POV 8% near-touch
Haitong short 450K shares 7226-HK limit 5.01, POV 5% passive 
MACQ short 216K shares 1783-HK limit 8.42, NEO 10%-15% 
MACQ cover 40.5K shares 9636-HK limit 37.9, NEO 10%-20% near-touch
MACQ SELL 1.3mn shares 600233-C1 limit 12.80, NEO 10%-15% 
Maybank cover 151.5K shares 1113-HK limit 32.85, POV 5% passive 
MBSO BUY 10K shares 002594-C2 limit 340.1, POV 1% passive
'''

In [5]:
text2=text.replace("  "," ").replace(" shares","").replace(" limit","").replace(",","").replace("CLSA Desk","CLSA_HT").replace("DESK POV","DESK").replace("Desk POV","DESK").replace(" HT","_HT").replace(" (low-touch)","").replace("~","").replace('passive ','passive').replace('MACQ','MEEX').replace('NEO','POV').replace('below ','1-').replace('near touch','neartouch').replace('near-touch ','NearTouch').replace('near-touch','NearTouch').replace('Low','5-10%').replace('Mid','10-20%').replace('High','15-30%').replace('Maybank','MKEA').replace('MBSO','MBSO_HT').replace('CGSI swap','CGPBS')
tradelist=[trades.rstrip().split(" ") for trades in text2.split("\n") if trades != ""]
#tradelist

In [6]:
cimblist=[ " ".join(x[1:]) for x in tradelist if "CIMB" in x]
for order in cimblist:
    print(order)

In [7]:
header=['Broker','Side','Quantity','Ticker','Price','Strategy','Vol(%)','Style']

In [8]:
def qty_conv(q):
    if q[-2:].lower() in ['mn','mm'] :
        qty=int(float(q[:-2])*1000000)
    elif q[-1].lower()=='k':
        qty=int(float(q[:-1])*1000)
    else:
        qty=int(q)
    
    return qty
def price_conv(p):
    if str(p)[-1].lower()=='k':
        p=float(p[:-1])*1000
    return p

In [9]:
tradeframe=pd.DataFrame(tradelist,columns=header)
#tradeframe=pd.DataFrame(tradelist)
#tradeframe

In [10]:
tradeframe['Ticker']=tradeframe['Ticker'].map(lambda x: x.replace("-"," ")+" EQUITY")
tradeframe['Quantity']=tradeframe['Quantity'].map(qty_conv)
tradeframe['Price']=tradeframe['Price'].map(price_conv)
tradeframe['Vol(%)']=tradeframe['Vol(%)'].map(lambda x: x.replace("%","") if x is not None else x)
tradeframe['Side']=tradeframe['Side'].map(lambda x:x.upper())
tradeframe['Side']=tradeframe['Side'].map({'SHORT':'SHRT','COVER':'COVR',"BUY":"BUY","SELL":'SELL'})
#tradeframe

In [11]:
brokers=['CLSA','CLSA_HT','Huatai','Huatai_HT','CICC_HT','CICC','Haitong','Haitong_HT','MEEX','MKEA','JEFS','JEFC','MBSO_HT','CGPBS','CGPBC']

In [12]:
tradeframe2=tradeframe[tradeframe['Broker'].isin(brokers)]
#tradeframe2
tradeframe2['Style']=tradeframe2.apply(lambda row: row['Style'].replace('passive','neartouch') if row['Broker']=='MEEX' and row['Style']=='passive' else row['Style'], axis=1)
tradeframe2['Vol(%)']=tradeframe2.apply(lambda row: str(float(row['Vol(%)'])/100) if row['Broker'] in ['CGPBS','CGPBC'] and ("-" not in row['Vol(%)']) else row['Vol(%)'], axis=1)
tradeframe2

,Broker,Side,Quantity,Ticker,Price,Strategy,Vol(%),Style
0,CGPBS,BUY,500000,291 HK EQUITY,24.30,POV,0.05,passive
1,Huatai,SELL,400000,2156 HK EQUITY,2.65,POV,12,passive
2,CLSA,COVR,3000000,601328 CH EQUITY,7.68,DESK,5,passive
3,CLSA,COVR,136000,1121 HK EQUITY,1.54,POV,15,NearTouch
4,CLSA,SHRT,40500,9636 HK EQUITY,40.50,POV,6,passive
5,CLSA,SHRT,155000,2473 HK EQUITY,6.65,POV,12,passive
6,CLSA,COVR,1000000,2202 HK EQUITY,4.76,POV,5,NearTouch
7,CLSA,COVR,250000,1280 HK EQUITY,3.28,POV,8,NearTouch
8,Haitong,SHRT,450000,7226 HK EQUITY,5.01,POV,5,passive
9,MEEX,SHRT,216000,1783 HK EQUITY,8.42,POV,10-15,None
10,MEEX,COVR,40500,9636 HK EQUITY,37.9,POV,10-20,NearTouch
11,MEEX,SELL,1300000,600233 C1 EQUITY,12.80,POV,10-15,None
12,MKEA,COVR,151500,1113 HK EQUITY,32.85,POV,5,passive
13,MBSO_HT,BUY,10000,002594 C2 EQUITY,340.1,POV,1,passive

In [13]:
tradeframe2.to_csv('trades_{}.csv'.format(tDay.strftime("%Y%m%d")),index=False)

In [14]:
quoteList=quote.replace("Quote borrow: ","").replace("quote borrow: ","").replace(":","").replace("Haitong","HT").replace("Guangfa","GF").split("/ ")
#quoteList

In [15]:
def quote(broker):    
    List=[x for x in quoteList if "(" not in x]+[x.split()[0] for x in quoteList if broker in x]
    String=broker+":\nHi team, could you quote borrow on "
    if broker=='Citi'or broker=='Tiger':
        List=[x for x in List if 'HK' in x]
    for x in List:
        String=String+x.strip()+", "
    String=String+"tks\n"
    String
    return String

In [16]:
brokerList=['GF','HT','CLSA','CICC','Huatai','MACQ','Tiger']#'CICC','MB','JEFF',,'Citi'
for broker in brokerList:
    print(quote(broker))

GF:
Hi team, could you quote borrow on 1280-HK, 2477-HK, 1196-HK, 412-HK, 7226-HK, 7552-HK, 9696-HK, 2359-HK, 3750-HK, 564-HK, 1072-HK, 600418-CH, 688256-CH, 042660-KS, 329180-KS, 7014-JP, tks

HT:
Hi team, could you quote borrow on 1280-HK, 2477-HK, 1196-HK, 412-HK, 7226-HK, 7552-HK, 9696-HK, 2359-HK, 3750-HK, 564-HK, 1072-HK, 600418-CH, 688256-CH, 042660-KS, 329180-KS, 7014-JP, tks

CLSA:
Hi team, could you quote borrow on 1280-HK, 2477-HK, 1196-HK, 412-HK, 7226-HK, 7552-HK, 9696-HK, 2359-HK, 3750-HK, 564-HK, 1072-HK, 600418-CH, 688256-CH, 042660-KS, 329180-KS, 7014-JP, tks

CICC:
Hi team, could you quote borrow on 1280-HK, 2477-HK, 1196-HK, 412-HK, 7226-HK, 7552-HK, 9696-HK, 2359-HK, 3750-HK, 564-HK, 1072-HK, 600418-CH, 688256-CH, 042660-KS, 329180-KS, 7014-JP, tks

Huatai:
Hi team, could you quote borrow on 1280-HK, 2477-HK, 1196-HK, 412-HK, 7226-HK, 7552-HK, 9696-HK, 2359-HK, 3750-HK, 564-HK, 1072-HK, 600418-CH, 688256-CH, 042660-KS, 329180-KS, 7014-JP, tks

MACQ:
Hi team, could you quote borrow on 1280-HK, 2477-HK, 1196-HK, 412-HK, 7226-HK, 7552-HK, 9696-HK, 2359-HK, 3750-HK, 564-HK, 1072-HK, 600418-CH, 688256-CH, 042660-KS, 329180-KS, 7014-JP, tks

Tiger:
Hi team, could you quote borrow on 1280-HK, 2477-HK, 1196-HK, 412-HK, 7226-HK, 7552-HK, 9696-HK, 2359-HK, 3750-HK, 564-HK, 1072-HK, tks

In [17]:
cimbList=[x for x in quoteList if "(" not in x]+[x.split()[0] for x in quoteList if "CIMB" in x]
shares=[1000000]*len(cimbList)
df=pd.DataFrame(shares,cimbList,columns=['qty'])
#csv_path='borrow.csv'
#df.to_csv('borrow.csv')
#os.system(f'start excel "{csv_path}"') 
df

                qty
1280-HK     1000000
2477-HK     1000000
1196-HK     1000000
412-HK      1000000
7226-HK     1000000
7552-HK     1000000
9696-HK     1000000
2359-HK     1000000
3750-HK     1000000
564-HK      1000000
1072-HK     1000000
600418-CH   1000000
688256-CH   1000000
042660-KS   1000000
329180-KS   1000000
7014-JP     1000000

In [18]:
mbList=[x for x in quoteList if "(" not in x]+[x.split()[0] for x in quoteList if "MB" in x]
shares=[1000000]*len(mbList)
df=pd.DataFrame(shares,mbList,columns=['qty'])
#csv_path='borrow.csv'
#df.to_csv('borrow.csv')
#os.system(f'start excel "{csv_path}"') 
df

                qty
1280-HK     1000000
2477-HK     1000000
1196-HK     1000000
412-HK      1000000
7226-HK     1000000
7552-HK     1000000
9696-HK     1000000
2359-HK     1000000
3750-HK     1000000
564-HK      1000000
1072-HK     1000000
600418-CH   1000000
688256-CH   1000000
042660-KS   1000000
329180-KS   1000000
7014-JP     1000000

In [19]:
macqList=[x for x in quoteList if "(" not in x]+[x.split()[0] for x in quoteList if 'MACQ' in x]
shares=[1000000]*len(macqList)
macq=pd.DataFrame(shares,macqList,columns=['quantity'])
macq=macq.reset_index()
macq.columns=['ticker','quantity']
def symbol(ticker):
    if ticker[-2:]=="CH":
        if ticker[0]=="6":
            ticker=ticker.replace("CH","SH")
        else:
            ticker=ticker.replace("CH","ZK")
    if ticker[-2:]=="HK":
        ticker=ticker.zfill(7)
    ticker=ticker.replace("-",".")
    return ticker
macq['ticker']=macq['ticker'].map(lambda x: x.replace(" ",""))
macq['ticker']=macq['ticker'].map(lambda x: symbol(x))
macq.loc[macq.shape[0]]=["1211.HK",500000]
macq.loc[macq.shape[0]]=["0300.HK",500000]
macq.loc[macq.shape[0]]=["0921.HK",500000]
csv_path='macqborrow.csv'
macq.to_csv('macqborrow.csv',index=False)
#os.system(f'start excel "{csv_path}"') 
macq

       ticker  quantity
0     1280.HK   1000000
1     2477.HK   1000000
2     1196.HK   1000000
3     0412.HK   1000000
4     7226.HK   1000000
5     7552.HK   1000000
6     9696.HK   1000000
7     2359.HK   1000000
8     3750.HK   1000000
9     0564.HK   1000000
10    1072.HK   1000000
11  600418.SH   1000000
12  688256.SH   1000000
13  042660.KS   1000000
14  329180.KS   1000000
15    7014.JP   1000000
16    1211.HK    500000
17    0300.HK    500000
18    0921.HK    500000